"""
build.py

A build script for slice thickness calculator, which bundles the project into a distributable directory using pyinstaller.
This script pulls the pysintaller .spec file, which details the specifics of the bundling process.
When the script is run, the user is prompted to enter a version number for the build. The suggested version number convention
is MAJOR.MINOR.REVISION.(BUILD), as is standard. The bundled project will be available in dist/

Written by Nathan Crossley, 2025.
"""

import subprocess
import sys
from pathlib import Path

# get user to pass in version number for build
version = input("Please enter version number for new build: ").strip()

# if no version number passed, abort
if not version:
    print("No version number entered, aborting build process.")
    sys.exit()

# get path for newly built project
dist_dir = Path(f"dist/slice_thickness_calculator_v{version}")

# run pyinstaller compilation via command line, using spec file for config
subprocess.run(
    [
        "pyinstaller",
        "--noconfirm",
        "--clean",
        "--distpath",
        str(dist_dir.resolve()),
        "slice_thickness_calculator.spec",
    ]
)

# move specific files out of _internal folder generated by pyinstaller,
# as required outside for runtime.
move_out_of_internal = ("config",)

for name in move_out_of_internal:
    path = dist_dir / "_internal" / name
    path.rename(dist_dir / name)
